### ISSUE TITLE
Network between container in the same group

### ISSUE THREAD

**Issue by gregoirefra** [Azure/aci-issues#19]
I might just not be enough aware of how everything is setup in the container but is there an internal address I can advertise to other container in the same group to point to one of the container?

Here is a little scenario to help. I have 3 container running in the same group. Container A is a reverse proxy, Container B is a sql database, Container C is a web application. Only A should be available from the web. Both container A and B are running there service on port 8080. The container C is running the SQL server on a dummy port like 5500. What is the address I should tell A to point towards the container B that as the application and the same for B to be aware of the SQL on C. 

Thanks in advance for the help

**Comment by dwrightpulse** [comment]
If you haven't found a solution to this yet, I'm using "localhost" to refer to other containers in the same group, and let the port identify which container is to be addressed.

I believe this is the "proper" way...

**Comment by gregoirefra** [comment]
Yeah I did that for a while but I hit some limitation with port and felt like it was messy because I had to refactor so many script that run in my container that it became to much of a pain. Ended up spinning up a Kubernetes cluster instead for the moment
