### ISSUE TITLE
Azure file share mount default to dir_mode=0700 and file_mode=0700

### ISSUE THREAD

**Issue by robberezowski** [Azure/aci-issues#27]
I'm developing a wordpress site on an Azure container instance and am using a mounted Azure file share for persistent storage.  This is a Linux container and I've been building it on VSTS. I've tried both the hosted linux preview agent and the newer ubuntu agent but the problem persists and I think this might be an Azure issue not a Docker issue.
 
I've followed the tutorial [here](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-volume-azure-files) using the last example to mount multiple volumes.  I'm not actually mounting multiple volumes but am using an ARM template to deploy this instance.

It was working fine but all of a sudden my website cannot write to the volume.  I've tried changing permissions with `chmod -R 777 /path/to/my/mount` and the command appears to work but the permissions do not change.

when I check the mount point with `cat /proc/mounts`  I can see the cifs mount but it has `dir_mode=0700` and `file_mode=0700` set.

I've tried updating the ARM template with `"readOnly": false` in both the volumes section and the volumeMounts section of the template with no effect. 

Is this a bug or is there a way to change the mount options in an ARM template for `dir_mode` and `file_mode`?

**Comment by mimckitt** [comment]
@seanmck could you help on this one?

**Comment by seanmck** [comment]
@jluk @yangl900

**Comment by yangl900** [comment]
Sorry for the issue! There was a bug that in a subset of deployments the file share mount has incorrect permissions.

I believe we have fixed the issue yesterday. Please let me know if this is still an issue.

**Comment by robberezowski** [comment]
Hi @yangl900 

This is working for me now. Are you able to put in an automated test around that? I lost a lot of time pulling my hair out on that one! 

Anyway, thanks for getting it fixed quickly

**Comment by yangl900** [comment]
Absolutely. There are tests added preventing this from regression again. Apologize for the time wasted. Please feel free to reach out to us here or via support channel, we are more than happy to help.
